site:
  title: Asset Administration Shell Documentation
  # url:
  start_page: index::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/rwth-iat/aas-specs
      branches: antora-docs
      start-paths: Part 1
ui:
  bundle:
    url: https://github.com/rwth-iat/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
    
runtime:
  fetch: true
