site:
  title: Asset Administration Shell Documentation
  url: https://rwth-iat.github.io/aas-specs-antora/
  start_page: index::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/rwth-iat/aas-specs
      branches: antora-docs
      start-paths: Part 1, Part 2, Part 5
      
    # - url: https://github.com/admin-shell-io/aas-specs-api
    #   branches: asciidoc
    #   start-paths: documentation
ui:
  bundle:
    url: https://github.com/rwth-iat/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
    
runtime:
  fetch: true
