site:
  url: https://admin-shell-io.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/admin-shell-io/aas-specs
      branches:
      - IDTA-01001-3-0_antora_ref
      - IDTA-01001-3-0-1_antora_ref
      - IDTA-01001-3-0-2_antora_ref
      - IDTA-01001-3-1_working
      start-paths: documentation/IDTA-01001
    - url: https://github.com/admin-shell-io/aas-specs-api
      branches:
      - IDTA-01002-3-0_antora_ref
      - IDTA-01002-3-0-2_antora_ref
      - IDTA-01002-3-0-3_antora_ref
      - IDTA-01002-3-1_preparation
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches:
      - IDTA-01003-a-3-0_antora_ref
      - IDTA-01003-a-3-0-2_antora_ref
      - IDTA-01003-a-3-1_working
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-security
      branches:
      - IDTA-01004-3-0_working
      start-paths: documentation/IDTA-01004
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches:
      - IDTA-01005-3-0_antora_ref
      - IDTA-01005-3-0-1_antora_ref
      - IDTA-01005-3-1_working
      start-paths: documentation/IDTA-01005

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
    - path: css/site-extra.css
      contents: |
        .breadcrumbs {
          display: flex;
          padding: 1rem 0;
          margin-bottom: 1rem;
          font-size: 0.9rem;
        }

        .page-title {
          color: #0033cc;
          font-size: 2rem;
          margin-bottom: 1.5rem;
        }

        .lead-paragraph {
          color: #666;
          font-size: 1rem;
          line-height: 1.5;
          margin-bottom: 2rem;
          max-width: 800px;
        }

        .specs-container {
          display: flex;
          justify-content: center;
          flex-wrap: wrap;
          gap: 1rem;
          padding: 0 1rem;
          margin: 0 auto;
        }

        .spec-card {
          width: 220px;
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
          margin-bottom: 2rem;
        }

        .image-box {
          width: 220px;
          height: 311px;
          margin-bottom: 1rem;
          border: 1px solid #e0e0e0;
        }

        .image-box img {
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
        }

        .text-box {
          width: 100%;
          min-height: 60px;
          margin-bottom: 0.5rem;
        }

        .spec-title {
          font-size: 0.9rem;
          color: #333;
          margin: 0;
          line-height: 1.4;
          font-weight: normal;
        }

        .spec-number {
          font-size: 0.8rem;
          color: #666;
          margin-top: 0.25rem;
        }

        .view-button {
          display: inline-flex;
          align-items: center;
          padding: 0.5rem 1rem;
          background: transparent;
          color: #0033cc;
          border: 1px solid #0033cc;
          border-radius: 4px;
          text-decoration: none;
          font-size: 0.9rem;
          margin-top: 0.5rem;
        }

        .view-button:hover {
          background: #0033cc;
          color: white;
        }

        .view-button::after {
          content: "→";
          margin-left: 0.5rem;
        }

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/refs/heads/main/plantuml/puml-theme-idta.puml
