site:
  url: https://industrialdigitaltwin.io/aas-specifications
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/admin-shell-io/aas-specs-metamodel
      branches:
      - IDTA-01001-3-0_antora_ref
      - IDTA-01001-3-0-1_antora_ref
      - IDTA-01001-3-0-2_antora_ref
      - IDTA-01001-3-2_Working
      - master
      start-paths: documentation/IDTA-01001
    - url: https://github.com/admin-shell-io/aas-specs-api
      branches:
      - IDTA-01002-3-0_antora_ref
      - IDTA-01002-3-0-2_antora_ref
      - IDTA-01002-3-0-3_antora_ref
      - IDTA-01002-3-0-4_antora_ref
      - IDTA-01002-3-2_Working
      - main
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches:
      - IDTA-01003-a-3-0_antora_ref
      - IDTA-01003-a-3-0-2_antora_ref
      - IDTA-01003-a-3-2_Working
      - main
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-security
      branches:
      - IDTA-01004-3-1_Working
      - main
      start-paths: documentation/IDTA-01004
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches:
      - IDTA-01005-3-0_antora_ref
      - IDTA-01005-3-0-1_antora_ref
      - IDTA-01005-3-2_Working
      - main
      start-paths: documentation/IDTA-01005

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
    - path: css/site-extra.css
      contents: |
        .breadcrumbs {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 1rem 0;
          color: #666;
          font-size: 0.875rem;
        }

        .breadcrumbs a {
          color: #0033cc;
          text-decoration: none;
        }

        .page-title {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
          font-size: 2rem;
          font-weight: 500;
          color: #0033cc;
          margin: 0 0 1.5rem;
        }

        .lead-paragraph {
          color: #666;
          font-size: 1rem;
          line-height: 1.5;
          margin-bottom: 3rem;
          max-width: 800px;
        }

        /* Horizontal cards container */
        .horizontal-cards {
          display: flex;
          flex-wrap: nowrap;
          gap: 2rem;
          justify-content: flex-start;
          padding: 2rem 0;
          overflow-x: auto;
        }

        /* Each card style */
        .card {
          flex: 0 0 auto;
          width: 220px;
          text-align: left;
          background-color: #fff;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          overflow: hidden;
        }

        .card img {
          width: 220px;
          height: 311px;
          margin-bottom: 1rem;
          object-fit: cover;
          display: block;
        }

        .card h2 {
          font-size: 1rem;
          font-weight: bold;
          margin: 0.5rem 0;
        }

        .card p {
          font-size: 0.875rem;
          line-height: 1.4;
          color: #666;
          margin-bottom: 1rem;
        }

        .view-button {
          display: inline-flex;
          align-items: center;
          padding: 0.5rem 1rem;
          background: transparent;
          color: #0033cc;
          border: 1px solid #0033cc;
          border-radius: 4px;
          text-decoration: none;
          font-size: 0.875rem;
          transition: all 0.2s ease;
        }

        .view-button:hover {
          background: #0033cc;
          color: white;
        }

        .view-button::after {
          content: "→";
          margin-left: 0.5rem;
        }

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    plantuml-format: svg
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specifications/main/plantuml/puml-theme-idta.puml
    pdf-theme: ./pdf-theme.yml