name: Publish Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  ## ──────────────────────────────────────────────────────────────────────
  ## Job #1: Build & publish HTML
  ## ──────────────────────────────────────────────────────────────────────
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with: { node-version: '18' }
      - name: Setup Java (for Kroki)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Install Kroki
        run: sudo apt update && sudo apt install -y graphviz
      - name: Generate HTML site
        run: npx antora antora-playbook.yml
      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  ## ──────────────────────────────────────────────────────────────────────
  ## Job #2: Build PDF (runs always, after checkout)
  ## ──────────────────────────────────────────────────────────────────────
   pdf:
    runs-on: ubuntu-latest
    needs: html
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js & Antora CLI + extensions
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          npm install --no-save \
            @antora/cli \
            @antora/pdf-extension \
            @antora/lunr-extension

      - name: Preprocess AsciiDoc for PDF only
        run: |
          find . -type f -name '*.adoc' -print0 \
            | xargs -0 sed -i \
                -e 's|<span class="underline">\([^<]*\)</span>|[.constraint]#\1#|g' \
                -e 's|<u>\([^<]*\)</u>|[.constraint]#\1#|g'

      - name: Build AAS-Specs PDF
        run: |
          npx antora \
            --generator @antora/pdf-extension \
            --to-dir build/pdf \
            antora-playbook.yml

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: aas-specs-pdf
          path: build/pdf/*.pdf
